src/Entity/Projets.php
<?php

namespace App\Entity;

use App\Repository\ProjetsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjetsRepository::class)]
class Projets
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateModification = null;

    #[ORM\OneToMany(mappedBy: 'IdProjet', targetEntity: Taches::class)]
    private Collection $taches;

    #[ORM\ManyToOne(inversedBy: 'projets')]
    private ?Utilisateurs $IdCreateur = null;

    public function __construct()
    {
        $this->taches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): static
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->DateModification;
    }

    public function setDateModification(\DateTimeInterface $DateModification): static
    {
        $this->DateModification = $DateModification;

        return $this;
    }

    /**
     * @return Collection<int, Taches>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Taches $tach): static
    {
        if (!$this->taches->contains($tach)) {
            $this->taches->add($tach);
            $tach->setIdProjet($this);
        }

        return $this;
    }

    public function removeTach(Taches $tach): static
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getIdProjet() === $this) {
                $tach->setIdProjet(null);
            }
        }

        return $this;
    }

    public function getIdCreateur(): ?Utilisateurs
    {
        return $this->IdCreateur;
    }

    public function setIdCreateur(?Utilisateurs $IdCreateur): static
    {
        $this->IdCreateur = $IdCreateur;

        return $this;
    }

    public function __toString(){
        return $this->Nom;
    }
}

src/Entity/Taches.php
<?php

namespace App\Entity;

use App\Repository\TachesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TachesRepository::class)]
class Taches
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Statut $IdStatut = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Projets $IdProjet = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateEcheance = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Utilisateurs $IdUtilisateur = null;

    public function __construct()
    {

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): static
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getIdStatut(): ?Statut
    {
        return $this->IdStatut;
    }

    public function setIdStatut(?Statut $IdStatut): static
    {
        $this->IdStatut = $IdStatut;

        return $this;
    }

    public function getIdProjet(): ?Projets
    {
        return $this->IdProjet;
    }

    public function setIdProjet(?Projets $IdProjet): static
    {
        $this->IdProjet = $IdProjet;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): static
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->DateEcheance;
    }

    public function setDateEcheance(\DateTimeInterface $DateEcheance): static
    {
        $this->DateEcheance = $DateEcheance;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateurs
    {
        return $this->IdUtilisateur;
    }

    public function setIdUtilisateur(?Utilisateurs $IdUtilisateur): static
    {
        $this->IdUtilisateur = $IdUtilisateur;

        return $this;
    }

    public function __toString(){
        return $this->Titre;
    }
}

src/Form/ProjetsType.php
<?php

namespace App\Form;

use App\Entity\Projets;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description')
            ->add('DateCreation')
            ->add('DateModification')
            ->add('IdCreateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projets::class,
        ]);
    }
}

src/Controller/ProjetsController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateurs;
use App\Entity\Projets;
use App\Form\ProjetsType;
use App\Repository\TachesRepository;
use App\Repository\ProjetsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/projets')]
class ProjetsController extends AbstractController
{
    #[Route('/', name: 'app_projets_index', methods: ['GET'])]
    public function index(ProjetsRepository $projetsRepository): Response
    {
        return $this->render('projets/index.html.twig', [
            'projets' => $projetsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_projets_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $projet = new Projets();
        $form = $this->createForm(ProjetsType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('app_projets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('projets/new.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projets_show', methods: ['GET'])]
    public function show(Projets $projet,TachesRepository $tachesRepository): Response
    {
        return $this->render('projets/kanban.html.twig', [
            'taches' => $tachesRepository->findByProjet($projet),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_projets_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Projets $projet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjetsType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_projets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('projets/edit.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projets_delete', methods: ['POST'])]
    public function delete(Request $request, Projets $projet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_projets_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/projets/_delete_form.html.twig
<form method="post" action="{{ path('app_projets_delete', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/projets/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/projets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projets{% endblock %}

{% block body %}
    <h1>Edit Projets</h1>

    {{ include('projets/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_projets_index') }}">back to list</a>

    {{ include('projets/_delete_form.html.twig') }}
{% endblock %}

templates/projets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets index{% endblock %}

{% block body %}
    <h1>Projets index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>DateCreation</th>
                <th>DateModification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for projet in projets %}
            <tr>
                <td>{{ projet.id }}</td>
                <td>{{ projet.Nom }}</td>
                <td>{{ projet.Description }}</td>
                <td>{{ projet.DateCreation ? projet.DateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ projet.DateModification ? projet.DateModification|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_projets_show', {'id': projet.id}) }}">Kanban</a>
                    <a href="{{ path('app_projets_edit', {'id': projet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    

    <a href="{{ path('app_projets_new') }}">Create new</a>
{% endblock %}

templates/projets/kanban.html.twig
{% include 'base.html.twig' %}
<link rel="stylesheet" href="{{asset("css/kanban.css")}}">
<body>
  <!-- Simple MDL Progress Bar -->
<div>
  <div class="test">
    <div id="p1" class="mdl-progress mdl-js-progress"></div>
          <h1><i class="material-icons">check</i> To do list</h1>
    </div>
    <menu class="kanban"><button><i class="material-icons">settings</i></button> <button><i class="material-icons">chevron_left</i></button>
      <button class="viewkanban"><i class="material-icons ">view_column</i></button>
      <button class="viewlist"><i class="material-icons">view_list</i></button>
      <button><i class="material-icons">playlist_add</i> Add new Column</button>
    </menu>
  </div>
  <div class="dd">
    <ol class="kanban To-do">
      <div class="kanban__title">
        <h2> A Faire</h2>
      </div>
      {% for tache in taches %}
      {% if tache.IdStatut == "A faire" %}
      <li class="dd-item" data-id="1">
        <h3 class="title dd-handle" >{{tache.titre}}</h3>
        <div class="text" contenteditable="true">
          {{tache.description}}
        </div> 
        <i class="material-icons" id="label blue">label</i>
        <div class="actions">
          <div class="text"><i class="fa-solid fa-pen"></i><a href="">Edit</a></div>
        </div>
      </li>
      {% endif %}
      {% endfor %}
      <div class="actions">
        <button class="addbutt"><i class="fa-solid fa-plus"></i><a href="{{ path('app_taches_new')}}"> Add new</a></button>
      </div>
    </ol>
    <ol class="kanban progress">
      <h2>En Cours</h2>
      {% for tache in taches %}
        {% if tache.IdStatut == "En Cours" %}
        <li class="dd-item" data-id="5">
        <h3 class="title dd-handle">{{tache.titre}}</h3>
          <div class="text" contenteditable="true">{{tache.description}}</div><div class="actions">
          <i class="material-icons">palette</i><i class="material-icons">edit</i><i class="material-icons">insert_link</i><i class="material-icons">attach_file</i></div>
        
        </li>
        {% endif %}
      {% endfor %}
      <div class="actions">
        <button class="addbutt"><i class="fa-solid fa-plus"></i><a href="{{ path('app_taches_new')}}"> Add new</a></button>
      </div>
    </ol>
    <ol class="kanban  Done">
      <h2>A Tester</h2>
      {% for tache in taches %}
        {% if tache.IdStatut == "A tester" %}
        <li class="dd-item" data-id="5">
          <h3 class="title dd-handle">{{tache.titre}}</h3>
          <div class="text" contenteditable="true">{{tache.description}}</div><div class="actions">
          <i class="material-icons">palette</i><i class="material-icons">edit</i><i class="material-icons">insert_link</i><i class="material-icons">attach_file</i></div>
        
        </li>
        {% endif %}
      {% endfor %}
      <div class="actions">
        <button class="addbutt"><i class="fa-solid fa-plus"></i><a href="{{ path('app_taches_new')}}"> Add new</a></button>
      </div>
    </ol>
    <ol class="kanban Gone">
      <h2>Faits</h2>
      {% for tache in taches %}
        {% if tache.IdStatut == "A tester" %}
      <li class="dd-item" data-id="5">
        <h3 class="title dd-handle">{{tache.titre}}</h3>
          <div class="text" contenteditable="true">{{tache.description}}</div>
          <div class="actions">
          <i class="material-icons">palette</i><i class="material-icons">edit</i><i class="material-icons">insert_link</i><i class="material-icons">attach_file</i></div>
        
      </li>
      {% endif %}
      {% endfor %}
      <div class="actions">
        <button class="addbutt"><i class="fa-solid fa-plus"></i><a href="{{ path('app_taches_new')}}"> Add new</a></button>
      </div>
    </ol>
  </div>
</div>
  <script>
    document.querySelector('#p1').addEventListener('mdl-componentupgraded', function() {
      this.MaterialProgress.setProgress(44);
    });
  </script><div class="kanban__title">
  <script src="{{asset("js/script.js")}}"></script>
  <script src="https://kit.fontawesome.com/002ad39ea0.js" crossorigin="anonymous"></script>
</body>
</html>

templates/projets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projets{% endblock %}

{% block body %}
    <h1>Create new Projets</h1>

    {{ include('projets/_form.html.twig') }}

    <a href="{{ path('app_projets_index') }}">back to list</a>
{% endblock %}

templates/projets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets{% endblock %}

{% block body %}
    <h1>Projets</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ projet.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ projet.Nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ projet.Description }}</td>
            </tr>
            <tr>
                <th>DateCreation</th>
                <td>{{ projet.DateCreation ? projet.DateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateModification</th>
                <td>{{ projet.DateModification ? projet.DateModification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_projets_index') }}">back to list</a>

    <a href="{{ path('app_projets_edit', {'id': projet.id}) }}">edit</a>

    {{ include('projets/_delete_form.html.twig') }}
{% endblock %}